stages:
  - build
  - tests
  - deploy

build:
  stage: build
  image: golang:1.14
  script:
    - go build ./...

linters:
  stage: tests
  image: golangci/golangci-lint
  script:
    - golangci-lint run ./...

unit-tests:
  stage: tests
  image: golang:1.14
  before_script:
    - go get -u github.com/jstemmer/go-junit-report
  script:
    - go test -v -race -count 100 internal/test/dbmigrator_test.go 2>&1 | go-junit-report > report.xml
  artifacts:
    paths:
      - report.xml

deploy:
  stage: deploy
  script:
    - echo "DEPLOY!"
  when: manual
